apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttt-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ttt
  template:
    metadata:
      labels:
        app: ttt
    spec:
      containers:
        - name: server
          image: ttt-server:latest
          ports:
            - containerPort: 8080
